// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-12-22 14:47:27.6516752 +0800 CST m=+1.620064801

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/HelloHandler": {
            "get": {
                "description": "这是第一个API",
                "tags": [
                    "文章"
                ],
                "summary": "第一个API",
                "responses": {
                    "200": {},
                    "400": {}
                }
            }
        },
        "/note": {
            "get": {
                "tags": [
                    "Note"
                ],
                "summary": "获取Note",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Note",
                        "name": "noteID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {}
                }
            },
            "post": {
                "tags": [
                    "Note"
                ],
                "summary": "新建Note",
                "parameters": [
                    {
                        "description": "Note",
                        "name": "note",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/service.CreateNoteParams"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {}
                }
            }
        },
        "/note/list": {
            "get": {
                "tags": [
                    "Note"
                ],
                "summary": "获取NoteList",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Note",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {}
                }
            }
        },
        "/user": {
            "get": {
                "tags": [
                    "用户"
                ],
                "summary": "通过ID获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {}
                }
            },
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "新建用户",
                "parameters": [
                    {
                        "description": "用户",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/service.CreateUserParams"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {}
                }
            }
        },
        "/user/token": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户获取token",
                "parameters": [
                    {
                        "description": "用户",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/service.CreateTokenParams"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {}
                }
            }
        }
    },
    "definitions": {
        "service.CreateNoteParams": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "service.CreateTokenParams": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "service.CreateUserParams": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
