definitions:
  service.CreateNote:
    properties:
      content:
        type: string
      err:
        type: error
      preView:
        type: string
      result:
        type: object
      title:
        type: string
    required:
    - content
    - title
    type: object
  service.CreateTokenParams:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  service.CreateUserParams:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
  license: {}
paths:
  /HelloHandler:
    get:
      description: 这是第一个API
      responses:
        "200": {}
        "400": {}
      summary: 第一个API
      tags:
      - 文章
  /note:
    get:
      parameters:
      - description: Note
        in: query
        name: noteID
        required: true
        type: integer
      responses:
        "200": {}
        "400": {}
      summary: 获取Note
      tags:
      - Note
    post:
      parameters:
      - description: Note
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/service.CreateNote'
          type: object
      responses:
        "200": {}
        "400": {}
      summary: 新建Note
      tags:
      - Note
  /note/list:
    get:
      parameters:
      - description: Note
        in: query
        name: page
        required: true
        type: integer
      responses:
        "200": {}
        "400": {}
      summary: 获取NoteList
      tags:
      - Note
  /user:
    get:
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200": {}
        "400": {}
      summary: 通过ID获取用户信息
      tags:
      - 用户
    post:
      parameters:
      - description: 用户
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.CreateUserParams'
          type: object
      responses:
        "200": {}
        "400": {}
      summary: 新建用户
      tags:
      - 用户
  /user/token:
    post:
      parameters:
      - description: 用户
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.CreateTokenParams'
          type: object
      responses:
        "200": {}
        "400": {}
      summary: 用户获取token
      tags:
      - 用户
swagger: "2.0"
