definitions:
  service.CreateNoteParams:
    properties:
      authorID:
        type: integer
      content:
        type: string
    required:
    - authorID
    - content
    type: object
  service.CreateTokenParams:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  service.CreateUserParams:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
  license: {}
paths:
  /HelloHandler:
    get:
      description: 这是第一个API
      responses:
        "200": {}
        "400": {}
      summary: 第一个API
      tags:
      - 文章
  /note:
    post:
      parameters:
      - description: Note
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.CreateNoteParams'
          type: object
      responses:
        "200": {}
        "400": {}
      summary: 新建Note
      tags:
      - Note
  /user:
    get:
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200": {}
        "400": {}
      summary: 通过ID获取用户信息
      tags:
      - 用户
    post:
      parameters:
      - description: 用户
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.CreateUserParams'
          type: object
      responses:
        "200": {}
        "400": {}
      summary: 新建用户
      tags:
      - 用户
  /user/token:
    post:
      parameters:
      - description: 用户
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.CreateTokenParams'
          type: object
      responses:
        "200": {}
        "400": {}
      summary: 用户获取token
      tags:
      - 用户
swagger: "2.0"
