definitions:
  user.createUserParams:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
  license: {}
paths:
  /HelloHandler:
    get:
      description: 这是第一个API
      responses:
        "200": {}
        "400": {}
      summary: 第一个API
      tags:
      - 文章
  /user:
    get:
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      responses:
        "200": {}
        "400": {}
      summary: 通过邮箱获取用户信息
      tags:
      - 用户
    post:
      parameters:
      - description: 用户
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.createUserParams'
          type: object
      responses:
        "200": {}
        "400": {}
      summary: 新建用户
      tags:
      - 用户
swagger: "2.0"
