definitions:
  dao.User:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  handler.CreateUserParams:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  handler.Test:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /HelloHandler:
    get:
      description: 实际并没有什么用只是用来看看的
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Test'
        "400": {}
      summary: 第一个API
      tags:
      - 文章
  /helper:
    get:
      description: 实际并没有什么用只是用来看看的
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Test'
        "400": {}
      summary: helper
      tags:
      - 文章
  /user:
    post:
      parameters:
      - description: 用户
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.CreateUserParams'
          type: object
      responses:
        "200":
          description: 成功后返回值
          schema:
            $ref: '#/definitions/dao.User'
        "400":
          description: fail" "失败后返回值
          schema:
            type: string
      summary: 新建用户
      tags:
      - 用户
  /user/info:
    get:
      parameters:
      - description: 用户的邮箱
        in: query
        name: email
        required: true
        type: string
      responses:
        "200":
          description: 成功后返回值
          schema:
            $ref: '#/definitions/dao.User'
        "400":
          description: fail" "失败后返回值
          schema:
            type: string
      summary: 通过邮箱获取用户信息
      tags:
      - 用户
swagger: "2.0"
